### ISSUE TITLE
issue about the numbers on MBLBP 

### ISSUE THREAD

**Issue by chibai** [tgy/facedetect#2]
According the original paper, there're 256 kinds of binary patterns and totally 2049 MB-LBP features.
But in your extraction phase, 
![image](https://cloud.githubusercontent.com/assets/5702248/23602565/213d22d0-028c-11e7-91f4-c81676614105.png)
I can understand the idea of your approach
I just want to know if you figure out 256 and 2049 these two numbers, cause I can not really map 256 and 2049 to your  method.
Thank you

**Comment by choucavalier** [comment]
I investigated this when I worked on this project and created [this script](https://github.com/tgy/facedetect/blob/master/script/compute_nb_of_features.py) to count the number of features for given window and block sizes. In the end I couldn't get the same number of features as described in the original paper. I decided it wasn't that important after all. If you ever find out, I'm interested to know.
